### PR TITLE
add frontend doc

### PR DESCRIPTION
**Pull request by unru-jo**
### Title: 📚 Update Frontend Documentation

**Description:**

🌟 This PR enhances the Federated Learning Demonstrator Frontend documentation. It aims to improve user understanding and interaction through clearer, more detailed guides.

Let's make our documentation as helpful as our technology! 🚀

### CODE REVIEW

**Comment by unru-jo** [comment]
please review @HeinrichAD @BeFranke

**Comment by BeFranke** [comment]
Some Thoughts:
- Generally pretty short, would be good to expand the individual sections
- More details (and how the process works in the background) would be nice
- References to MNIST Tutorial would be nice where it makes sense
- Introduction:
	- By the German Aerospace Center (DLR)
- Features (Redundant Headline with one 1 subsection):
	- Dashboard:
		- "Metrics" instead of "Accuracy"
		- Could it be that the point "Node Connectivity" is promising a bit too much? Afaik we can only see which participants a training has, has this changed?
- Usage:
	- Navigating the Dashboard:
		- "Interpreting Data Visualization" not clear
		- Initiating a Training Process: Should at least reference tutorial to show how to set up the nodes

**Comment by BeFranke** [comment]
- Please further expand the individual sections
- At least some images would be very nice
- If the video is no longer included, remove the plugin for the video
- References to MNIST Tutorial would be nice where it makes sense (including link!)
- More details (and how the process works in the background) would be nice


Please ignore if you are still on it, just thought about giving my 2 cents

**Comment by BeFranke** [comment]
Merging for now for release 1.0, please continue work in #3

**Pull request merged**
